title: "SonarQube Deployment"
stackDescription: Deploy SonarQube in Oracle Cloud Infrastructure
schemaVersion: 1.2.0
version: "20201104"
locale: "en"

variableGroups:
  - title: General Configuration
    visible: false
    variables:
      - tenancy_ocid
      - region
      - use_marketplace_image
      - fingerprint
      - private_key_path
      - image_ocid

  - title: Required Configuration
    visible: true
    variables:
      - compartment_ocid
      - availability_domain
      - show_advanced

  - title: Network Optional Configuration
    visible:
      and:
        - show_advanced
    variables:
      - vcn_cidr

  - title: Compute Optional Configuration
    visible:
      and:
        - show_advanced
    variables:
      - ssh_public_key
      - generate_public_ssh_key
      - instance_os
      - linux_os_version
      - node_shape
      - node_flex_shape_ocpus
      - node_flex_shape_memory
      - instance_shape

variables:
  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Compartment
    description: Compartment where you want to create the solution resources.
    default: ""

  region:
    type: oci:identity:region:name
    required: true
    visibile: true
    title: "Region"

  availability_domain:
    type: oci:identity:availabilitydomain:name
    required: true
    visibile: true
    title: "Availability Domain to be chosen"
    description: "Choose Availability Domain where your SonarQube will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  vcn_cidr:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose VCN CIDR for your SonarQube deployments."

  generate_public_ssh_key:
    type: boolean
    title: "Auto-generate public ssh key?"
    description: "Auto-generate a public key and assign to the compute instances. Uncheck to provide your own public key or leave blank not to use any attach any key to the compute instance."
    visible:
      and:
        - show_advanced

  public_ssh_key:
    type: oci:core:ssh:publickey
    title: "SSH Public Key"
    description: "The public SSH key for the key-pair that you want to use, if you wish to login to the instances over SSH."
    additionalProps:
      allowMultiple: true
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
    visible:
      and:
        - and:
            - show_advanced
        - not:
            - generate_public_ssh_key

  node_shape:
    type: oci:core:instanceshape:name
    required: true
    title: "SonarQube instance shape"
    description: "Choose Instance Shape for SonarQube."
    default: "VM.Standard.E3.Flex"
    dependsOn:
      compartmentId: ${compartment_ocid}

  node_flex_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
            - eq:
                - node_shape
                - "VM.Standard.E3.Flex"
            - eq:
                - node_shape
                - "VM.Standard.E4.Flex"

  node_flex_shape_memory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 10
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
            - eq:
                - node_shape
                - "VM.Standard.E3.Flex"
            - eq:
                - node_shape
                - "VM.Standard.E4.Flex"

  instance_os:
    type: enum
    required: false
    title: "Instance OS"
    description: "An Operating System that determines the operating system for SonarQube host."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for SonarQube host."
    default: "8"
    enum:
      - "7"
      - "8"

outputGroups:
  - title: "SonarQube App details"
    outputs:
      - generated_private_key_pem
      - sonarQube_public_url

outputs:
  generated_private_key_pem:
    type: string
    title: "Generated Private Key for SSH Access"
    displayText: "Generated Private Key for ssh access to compute nodes"
    visible: true

  sonarQube_public_url:
    type: link
    title: Open
    visible: true
