#cloud-config
bootcmd:
  - [
      cloud-init-per,
      once,
      enable-epel,
      yum-config-manager,
      --enable,
      ol7_developer_epel,
    ]
groups:
  - docker
users:
  - default
  - name: opc
    groups: docker
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

packages:
  - docker-engine
  - docker-ce
  - docker-ce-cli

runcmd:
  - firewall-offline-cmd --zone=public --add-port=9000/tcp
  - systemctl restart firewalld
  - [systemctl, daemon-reload]
  - [systemctl, enable, docker.service]
  - [systemctl, start, --no-block, docker.service]
  - [touch, /tmp/cloud-init-complete]
